version: '3.8'
services:
  mongodb:
    image: mongo
    expose:
      - '27017'
  web:
    image: node:12
    working_dir: /app
    restart: on-failure:5
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - '8080'
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb/eeplus
      PORT: '8080'
    tty: true
    stdin_open: true
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - web:web
    ports:
      - 8888:80
